version: '3.9'
services:
  jack_server:
    container_name: jack_server
    build:
      dockerfile: Dockerfile 
      context: ./server/
    volumes:
      - ./server/:/jack/server/
    ports:
      - 8080:8080
    links:
      - jack_database
  jack_database:
    container_name: jack_database
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=jack
    ports:
      - 5432:5432
    volumes:
      - jack_database:/var/lib/postgresql/data
volumes:
  jack_database:
    driver: local